### ISSUE TITLE
Realtime publisher crashing ros2 foxy

### ISSUE THREAD

**Issue by jlack1987** [ros-controls/realtime_tools#95]
Have encountered a number of times lately where the `realtime_tools::RealtimePublisher` segfaults. Here is a stack trace from gdb,
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f571aeb3859 in __GI_abort () at abort.c:79
#2  0x00007f570198f25b in expand_var.cold () at /opt/nauticus/foxy_src/cyclonedds/lib/libddsc.so.0
#3  0x00007f5701a1c888 in dds_log () at /opt/nauticus/foxy_src/cyclonedds/lib/libddsc.so.0
#4  0x00007f57019ec691 in lookup_thread_state_real () at /opt/nauticus/foxy_src/cyclonedds/lib/libddsc.so.0
#5  0x00007f5701a11875 in dds_write_impl () at /opt/nauticus/foxy_src/cyclonedds/lib/libddsc.so.0
#6  0x00007f5701a118e2 in dds_write () at /opt/nauticus/foxy_src/cyclonedds/lib/libddsc.so.0
#7  0x00007f5701a92334 in rmw_publish () at /opt/nauticus/foxy_src/rmw_cyclonedds_cpp/lib/librmw_cyclonedds_cpp.so
#8  0x00007f5701c846f6 in rcl_publish () at /opt/nauticus/foxy_src/rcl/lib/librcl.so
#9  0x00007f551fc83bd3 in rclcpp::Publisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> >, std::allocator<void> >::do_inter_process_publish(geometry_msgs::msg::PoseStamped_<std::allocator<void> > const&) (this=0x7f5549feeea0, msg=...) at /opt/nauticus/foxy_src/rclcpp/include/rclcpp/publisher.hpp:282
#10 0x00007f551fc7a268 in rclcpp::Publisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> >, std::allocator<void> >::publish(geometry_msgs::msg::PoseStamped_<std::allocator<void> > const&)
    (this=0x7f5549feeea0, msg=...) at /opt/nauticus/foxy_src/rclcpp/include/rclcpp/publisher.hpp:214
#11 0x00007f551fc84dd2 in realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::publishingLoop() (this=0x7f5549e9e280)
    at /opt/ros/foxy/include/realtime_tools/realtime_publisher.h:188
#12 0x00007f551fcec7c0 in std::__invoke_impl<void, void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*>(std::__invoke_memfun_deref, void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*&&)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*&&)
    (__f=@0x7f5549fee8c0: (void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(class realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > > * const)) 0x7f551fc84c2a <realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::publishingLoop()>, __t=@0x7f5549fee8b8: 0x7f5549e9e280) at /usr/include/c++/9/bits/invoke.h:73
#13 0x00007f551fcec203 in std::__invoke<void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*>(void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*&&)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*&&)
    (__fn=@0x7f5549fee8c0: (void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(class realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > > * const)) 0x7f551fc84c2a <realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::publishingLoop()>)
    at /usr/include/c++/9/bits/invoke.h:95
#14 0x00007f551fceb901 in std::thread::_Invoker<std::tuple<void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) (this=0x7f5549fee8b8) at /usr/include/c++/9/thread:244
#15 0x00007f551fcea646 in std::thread::_Invoker<std::tuple<void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*> >::operator()() (this=0x7f5549fee8b8) at /usr/include/c++/9/thread:251
#16 0x00007f551fce8e4e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >::*)(), realtime_tools::RealtimePublisher<geometry_msgs::msg::PoseStamped_<std::allocator<void> > >*> > >::_M_run() (this=0x7f5549fee8b0) at /usr/include/c++/9/thread:195
#17 0x00007f571b174de4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007f571aa71609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#19 0x00007f571afb0133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
I'm not sure if this is helpful or not since it's all built in `Release`, but I have encountered this crash a number of times recently. On ros2 foxy

**Comment by christophfroehlich** [comment]
Seems to be no issue any more if noone else has reported this.
